### ISSUE TITLE
Credible interval for tempo-activity-plot

### ISSUE THREAD

**Issue by rdinapoli** [ArchaeoStat/ArchaeoPhases#19]
Hello,

I would like to compute and plot a credible interval for `tempo_activity_plot`, but I can't seem to find a solution. Are there any plans to add this functionality?

Thanks,
Robert

**Comment by philippe-a** [comment]
Hello 
In the current version it is not possible to add credibility intervals. 
This raises theoretical questions of statistics that we have not yet solved 
We hope to be able to quickly implement a solution ! 
Best regards 
Anne

**Comment by rdinapoli** [comment]
Hi Anne,

Thanks for your response. If you have time, can you elaborate on what you mean by 'theoretical questions of statistics'?

Thanks,
Robert

**Comment by philippe-a** [comment]
Hi Robert 

The problem to  obtain  credible interval on the activity curve is evaluate  the error on this  function from the posterior probability distribution on the dates.

Anne

**Comment by rdinapoli** [comment]
Thanks for the information!
